spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/foreign_exchange_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false